# Generated by Django 5.2.5 on 2025-09-01 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_message_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_mode', models.CharField(default='dynamic', verbose_name='translation_mode')),
            ],
        ),
        migrations.DeleteModel(
            name='ChatBot_Status',
        ),
        migrations.AddField(
            model_name='group',
            name='state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.chatbot_state'),
        ),
    ]
