# Generated by Django 5.2.5 on 2025-09-02 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_chatbot_state_delete_chatbot_status_group_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='language',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
